version: '3'

services:
  web:
    image: tomcat:jdk15
    ports:
      - 8080:8080
    volumes:
      - ./target/:/usr/local/tomcat/webapps/
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bbs
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - "TZ=Asia/Tokyo"
    ports:
      - 3306:3306